# -*- coding: utf-8 -*-
"""python.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sA-Ss9SEX25J1-gPVvy05pdefnz15LtP
"""

#palindrome
n=input()
strreverse=n[::-1]
if n==strreverse:
  print("it is palindrome")
else:
  print("it is not palindrome")

#largestnumber
a=int(input())
b=int(input())
if a>b:
  print("a is greater")
elif b>a:
  print("b is greater")
else:
  print("equal")

#factorial
x=int(input())
fact=1
while x>1:
  fact*=x
  x=x-1
print(fact)

#amstrongnumber
f=int(input())
f_digit=len(str(f))
temp=f
sum=0
while temp>0:
  digit=temp%10
  sum+=digit**f_digit
  temp=temp//10
print (sum)
if sum==f:
  print("valid")
else:
  print("invalid")

#primenumber
for num in range(0,51):
  if num>1:
    is_prime=True
    for i in range(2,num):
      if num%i==0:
       is_prime=False
       break
    if is_prime:
      print(num)

#celisus to f
c=float(input())
f=(c*9/5)+32
print(f)

#swap
a=int(input())
b=int(input())
a,b=b,a
print(a)
print(b)

#fibonacci
a=0
b=1
print(a)
print(b)
for i in range(10):
  c=a+b
  a=b
  b=c
  print(c)

#largest of three
a=int(input())
b=int(input())
c=int(input())
if a>b and a>c:
  print("a is greater")
elif b>a and b>c:
  print("b is greater")
else:
  print("c is greater")

#average
a=int(input())
b=int(input())
c=int(input())
average=a+b+c/3
print(average)

#vowels count and word count
t=input()
vowels="aeiouAEIOU"
count=0
wordcount=0
for i in t:
  if i in vowels:
    print(i,end="")
    count+=1
for i in t:
  print(i,end="")
  wordcount+=1
print("\n", count)
print("\n" ,wordcount)

#sliceing
s=input()
b=s[1:-1]
print(b)

#gcd and lcm
a=int(input())
b=int(input())
x=a
y=b
while y!=0:
  x,y=y,x%y
gcd=x
lcm=(a*b)//gcd
print(gcd)
print(lcm)

#find max and min in list
l=[3,17,29,7,65,92]
print(max(l))
print(min(l))

#calculator
a=int(input())
b=int(input())
print("add",a+b)
print("sub",a-b)
print("mul",a*b)
print("div",a/b)

#positive negative zero
n=int(input())
if n>0:
  print("positive")
elif n==0:
  print("zero")
else:
  print("negative")

#leap year
n=int(input())
if n%400==0 or n%4==0 and n%100 !=0 :
  print("leap year")
else:
  print("not leap year")

#even or odd
n=int(input())
if n%2==0:
  print("even")
else:
  print("odd")

#annagram
a=input()
b=input()
if sorted(a)==sorted(b):
  print("annagram")
else:
  print("not annagram")

#patterns
for i in range (1,6):
  for j in range (1,i+1):
    print(j,end="")
  print()

#patterns
for i in range(6,0,-1):
  for j in range(1,i+1):
    print("*",end="")
  print()

#patterns
n=6
for i in range(n):
  print(" "* i +"*"*(n-i))

#pattern
n=3
for i in range(1,n+1):
  print(" "* (n-i)+"* "*i)
for i in range(n-1,0,-1):
  print(" "* (n-i)+"* " *i)

n=5
for i in range(1,n+1):
  print(" "*(n-i)+"* "*i)

#find largest 3 numbers without if else
import numpy as np
arr=np.array([10,222,13,53,64])
c=np.sort(arr)
print(c)
print(c[4],c[3],c[2])

#check anagram without sorted()
n=input()
m=input()
if (n==m,m==n):
  print("anagram")
else:
  print("not anagram")

# Check if a number is a power of 2 without using loops

n= int(input("Enter a number: "))

if n > 0 and (n & (n - 1)) == 0:
    print(n, "is a power of 2")
else:
    print(n, "is not a power of 2")

n = int(input("Enter a number: "))
rev = 0
while n > 0:
    digit = n % 10
    rev = rev * 10 + digit
    n = n // 10
print("Reversed number =", rev)

s = input()
c = ""
m = 0
for ch in s:
    if ch not in c:
        c = c + ch
    else:
        c = ch
    if len(c) > m:
        m = len(c)
print(m)

s="forgeeksskeegfor"
b=s[3:13:1]
if b==b[::-1]:
  print(b)

s=input()
st=s.lower()
v="aeiou"
r=0
vlist=[]
result=""
for ch in st:
  if ch in v:
    vlist.append(ch)
vlist.reverse()
for ch in st:
  if ch in v:
    result+=vlist[r]
    r+=1
  else:
    result+=ch
print(result)

str1=input()
str2=input()
if len(str1)!=len(str2):
  print("no")
else:
  count=0
  for i in range (len(str1)):
    if str1[i]!=str2[i]:
      count+=1
if count==1:
    print("yes")
else:
    print("no")

n=int(input())
x=list(map(int,input().split()))
for i in range (1,n+1):
  d=x[i]
  if x[i]==0:
    d=x[i-1]+1
    print(d)
    break

#class & ojects
class student:
  def __init__(self,name,age):
    self.name=name
    self.age=age
  def display(self):
    print("name:",self.name)
    print("age:",self.age)
obj=student("hems",3)
obj.display()

#inheritance
class father:
  def bike(self):
    print("father has a  bike")
class Son (father):
  def cycle(self):
    print("son has a cycle")
obj=Son()
obj.bike()

#abstraction
class bank:
  def __init__(self):
    self.balance=5000
  def show_balance(self):
    print("balance",self.balance)
obj=bank()
obj.show_balance()

def prime(n):
  if n>1:
    is_prime=True
    for i in range(2,n):
      if n%i==0:
       is_prime=False
       break
    if is_prime:
      print("it is prime")
n=int(input())
prime(n)
re=0
while n>0:
 d=n%10
 re=re*10+d
 n//=10
if prime(re) ==prime(n):
  print("both prime")

n=int(input())
for i in range (n):
  if i%2==0:
    print("-",i)
  else:
    print(i)

def rev(n):
    r = 0
    while n > 0:
        digit = n % 10
        r = r * 10 + digit
        n //= 10
    return r
n = int(input())
sn = n ** 2
a = rev(n)
sr = a ** 2
if sorted(str(sn)) == sorted(str(sr)):
    print("success")
else:
    print("not success")

def prime(n):
    for i in range(2, n):
        if n % i == 0:
            return False
    return n > 1
n = input()
temp = n
flag = True
for i in range(len(n)):
    print(temp)
    if not prime(int(temp)):
        flag = False
    temp = temp[1:] + temp[0]
if flag:
    print("All are prime")
else:
    print("Not prime")

n=input()
a,b,c,d,e=map(int,input().split())
total=a+b+c+d+e
av=(a+b+c+d+e)/5
m=max(a,b,c,d,e)
if a<35:
  print("fail")
elif b<35:
  print("fail")
elif c<35:
  print("fail")
elif d<35:
  print("fail")
elif f<35:
  print("fail")
else:
  print("pass")

n=input()
a,b,c,d,e,k=map(int,input().split())
av=(a+b+c+d+e+k)//6
count=0
m=max(a,b,c,d,e,k)
for i in a,b,c,d,e,k:
  if i<=80:
    count+=1
print(m)
print(av)
print(count)

class ParkingLot:
    def __init__(self, vehicles):
        self.vehicles = vehicles
    def duplicates(self):
        dup = []
        for i in self.vehicles:
            if self.vehicles.count(i) > 1 and i not in dup:
                dup.append(i)
        return dup

    def unique_count(self):
        return len(set(self.vehicles))
vehicles = [101, 105, 110, 101, 115, 105]
p = ParkingLot(vehicles)

print("Duplicate Vehicles:", p.duplicates())
print("Unique Vehicles:", p.unique_count())

n=input()
a,b,c,d,e=map(int,input().split())
av=(a+b+c+d+e)/5
count=0
m=max(a,b,c,d,e)
mi=min(a,b,c,d,e)
for i in a,b,c,d,e:
  if i>=50:
    count+=1
print(m)
print(mi)
print(av)
print(count)

text = input("Enter text: ")
sub = input("Enter substring: ")

count = text.count(sub)

print("Occurrences =", count)

n=input()
a,b,c,d=map(int,input().split())
total=a+b+c+d
m=max(a,b,c,d)
print(total)
print(m)
if total>5000:
  discount=total*15/100
  print(discount)

n=input("patient:")
a,b,c,d,e=map(float,input("temperatures").split())
m=max(a,b,c,d,e)
mi=min(a,b,c,d,e)
r=0
for i in a,b,c,d,e:
  if i>100:
    r+=1
print(m)
print(mi)
print(r)

n=input()
a,b,c,d,e,k=map(int,input().split())
av=(a+b+c+d+e+k)//6
count=0
m=max(a,b,c,d,e,k)
mi=min(a,b,c,d,e,k)
for i in a,b,c,d,e,k:
  if i>=75:
    count+=1
print(m)
print(mi)
print(count)

a=input()
b=input()
if sorted(a)==sorted(b):
  print("anagram")
else:
  print("no")

#second largest value
n=[12,45,67,23,89,67]
largest = n[0]
second = n[0]
for i in n:
    if i > largest:
        second = largest
        largest = i
    elif i > second and i != largest:
        second = i
print(n)
print(second)

#unquie character in string
n=input()
for ch in n:
  if n.count(ch)==1:
    print(ch)
    break

#rotate list by k position
n=list(input())
k=2
result=a[-k:]+a[:-k]
print(result)

#odd even rearrangement
b=[7,2,5,4,9,8]
even=[]
odd=[]
for i in b:
  if i%2==0:
    even.append(i)
  else:
    odd.append(i)
r=even+odd
print(r)

#nested list sum
def total(lst):
  s=0
  for i in lst:
    if isinstance(i,list):
      s+=total(i)
    else:
      s+=i
  return s
print(total([1,[2,3],[4,[5,6]]]))

#pair of sum
arr = [2,7,11,15,3,6]
target = 9
for i in range(len(arr)):
    for j in range(i+1, len(arr)):
        if arr[i] + arr[j] == target:
            print((arr[i], arr[j]))

#lenght of consont in string
n=input()
a="aeiouAEIOU"
count=0
for i in n:
  if i not in a:
    count+=1
print(count)

#sum and product
for i in range (1,101):
  n=str(i)
  if (len(n)==1):
    print(i,end=" ")
  else:
    if((int(n[0])+int(n[1])==int(n[0])*int(n[1]))):
      print(i)

n=input()
print(int(max(n)))

