# -*- coding: utf-8 -*-
"""python.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sA-Ss9SEX25J1-gPVvy05pdefnz15LtP
"""

#palindrome
n=input()
strreverse=n[::-1]
if n==strreverse:
  print("it is palindrome")
else:
  print("it is not palindrome")

#largestnumber
a=int(input())
b=int(input())
if a>b:
  print("a is greater")
elif b>a:
  print("b is greater")
else:
  print("equal")

#factorial
x=int(input())
fact=1
while x>1:
  fact*=x
  x=x-1
print(fact)

#amstrongnumber
f=int(input())
f_digit=len(str(f))
temp=f
sum=0
while temp>0:
  digit=temp%10
  sum+=digit**f_digit
  temp=temp//10
print (sum)
if sum==f:
  print("valid")
else:
  print("invalid")

#primenumber
for num in range(0,51):
  if num>1:
    is_prime=True
    for i in range(2,num):
      if num%i==0:
       is_prime=False
       break
    if is_prime:
      print(num)

#celisus to f
c=float(input())
f=(c*9/5)+32
print(f)

#swap
a=int(input())
b=int(input())
a,b=b,a
print(a)
print(b)

#fibonacci
a=0
b=1
print(a)
print(b)
for i in range(10):
  c=a+b
  a=b
  b=c
  print(c)

#largest of three
a=int(input())
b=int(input())
c=int(input())
if a>b and a>c:
  print("a is greater")
elif b>a and b>c:
  print("b is greater")
else:
  print("c is greater")

#average
a=int(input())
b=int(input())
c=int(input())
average=a+b+c/3
print(average)

#vowels count and word count
t=input()
vowels="aeiouAEIOU"
count=0
wordcount=0
for i in t:
  if i in vowels:
    print(i,end="")
    count+=1
for i in t:
  print(i,end="")
  wordcount+=1
print("\n", count)
print("\n" ,wordcount)

#sliceing
s=input()
b=s[1:-1]
print(b)

#gcd and lcm
a=int(input())
b=int(input())
x=a
y=b
while y!=0:
  x,y=y,x%y
gcd=x
lcm=(a*b)//gcd
print(gcd)
print(lcm)

#find max and min in list
l=[3,17,29,7,65,92]
print(max(l))
print(min(l))

#calculator
a=int(input())
b=int(input())
print("add",a+b)
print("sub",a-b)
print("mul",a*b)
print("div",a/b)

#positive negative zero
n=int(input())
if n>0:
  print("positive")
elif n==0:
  print("zero")
else:
  print("negative")

#leap year
n=int(input())
if n%400==0 or n%4==0 and n%100 !=0 :
  print("leap year")
else:
  print("not leap year")

#even or odd
n=int(input())
if n%2==0:
  print("even")
else:
  print("odd")

#annagram
a=input()
b=input()
if sorted(a)==sorted(b):
  print("annagram")
else:
  print("not annagram")

#patterns
for i in range (1,6):
  for j in range (1,i+1):
    print(j,end="")
  print()

#patterns
for i in range(6,0,-1):
  for j in range(1,i+1):
    print("*",end="")
  print()

#patterns
n=6
for i in range(n):
  print(" "* i +"*"*(n-i))

#pattern
n=3
for i in range(1,n+1):
  print(" "* (n-i)+"* "*i)
for i in range(n-1,0,-1):
  print(" "* (n-i)+"* " *i)

n=5
for i in range(1,n+1):
  print(" "*(n-i)+"* "*i)

#find largest 3 numbers without if else
import numpy as np
arr=np.array([10,222,13,53,64])
c=np.sort(arr)
print(c)
print(c[4],c[3],c[2])

#check anagram without sorted()
n=input()
m=input()
if (n==m,m==n):
  print("anagram")
else:
  print("not anagram")

# Check if a number is a power of 2 without using loops

n= int(input("Enter a number: "))

if n > 0 and (n & (n - 1)) == 0:
    print(n, "is a power of 2")
else:
    print(n, "is not a power of 2")

n = int(input("Enter a number: "))
rev = 0
while n > 0:
    digit = n % 10
    rev = rev * 10 + digit
    n = n // 10
print("Reversed number =", rev)

s = input()
c = ""
m = 0
for ch in s:
    if ch not in c:
        c = c + ch
    else:
        c = ch
    if len(c) > m:
        m = len(c)
print(m)

s="forgeeksskeegfor"
b=s[3:13:1]
if b==b[::-1]:
  print(b)

s=input()
st=s.lower()
v="aeiou"
r=0
vlist=[]
result=""
for ch in st:
  if ch in v:
    vlist.append(ch)
vlist.reverse()
for ch in st:
  if ch in v:
    result+=vlist[r]
    r+=1
  else:
    result+=ch
print(result)

str1=input()
str2=input()
if len(str1)!=len(str2):
  print("no")
else:
  count=0
  for i in range (len(str1)):
    if str1[i]!=str2[i]:
      count+=1
if count==1:
    print("yes")
else:
    print("no")

n=int(input())
x=list(map(int,input().split()))
for i in range (1,n+1):
  d=x[i]
  if x[i]==0:
    d=x[i-1]+1
    print(d)
    break

#class & ojects
class student:
  def __init__(self,name,age):
    self.name=name
    self.age=age
  def display(self):
    print("name:",self.name)
    print("age:",self.age)
obj=student("hems",3)
obj.display()

#inheritance
class father:
  def bike(self):
    print("father has a  bike")
class Son (father):
  def cycle(self):
    print("son has a cycle")
obj=Son()
obj.bike()

#abstraction
class bank:
  def __init__(self):
    self.balance=5000
  def show_balance(self):
    print("balance",self.balance)
obj=bank()
obj.show_balance()

def prime(n):
  if n>1:
    is_prime=True
    for i in range(2,n):
      if n%i==0:
       is_prime=False
       break
    if is_prime:
      print("it is prime")
n=int(input())
prime(n)
re=0
while n>0:
 d=n%10
 re=re*10+d
 n//=10
if prime(re) ==prime(n):
  print("both prime")

n=int(input())
for i in range (n):
  if i%2==0:
    print("-",i)
  else:
    print(i)

def rev(n):
    r = 0
    while n > 0:
        digit = n % 10
        r = r * 10 + digit
        n //= 10
    return r
n = int(input())
sn = n ** 2
a = rev(n)
sr = a ** 2
if sorted(str(sn)) == sorted(str(sr)):
    print("success")
else:
    print("not success")

def prime(n):
    for i in range(2, n):
        if n % i == 0:
            return False
    return n > 1
n = input()
temp = n
flag = True
for i in range(len(n)):
    print(temp)
    if not prime(int(temp)):
        flag = False
    temp = temp[1:] + temp[0]
if flag:
    print("All are prime")
else:
    print("Not prime")

import os
os.environ["KAGGLE_USERNAME"]='vigneshkumarnew'
os.environ["KAGGLE_KEY"]='KGAT_236249ed4f11b377e12caaae42e56302'
!pip install kaggle

!kaggle datasets download -d /laveshjadon/ai-impact-on-students

!kaggle datasets list

!kaggle datasets download -d yasserh/titanic-dataset

import numpy as np
import pandas as pd
df=pd.read_csv("/content/ai-impact-on-students.zip")
df.head()

df.info()

df.shape

df.columns

df.isnull().sum()

df.describe()

df.sample(5)

df.nunique()

import pandas as pd
df=pd.read_csv("/content/titanic-dataset.zip")
df.head(10)

df.tail(10)

print(len(df))
print(df.shape)

df.duplicated().sum()

print(df.isnull().sum())

df['Age'].fillna(df['Age'].median(),inplace=True)
print(df[['Age']].head(10))
print(df.isnull().sum())

